version: '3.8'

services:
  # Backend API Service 
  api:
    container_name: gdpr_api_backend
    build: .
    ports:
      - "8000:80" 
    # Uvicorn for the main API module
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
    restart: always

  # Frontend Streamlit 
  frontend:
    container_name: gdpr_frontend_streamlit
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501" 
    depends_on:
      - api
    restart: always
